# Configuração do Ruff para o projeto Flask
# Compatível com Black e modernas práticas de Python

# Configurações gerais
line-length = 88  # Padrão do Black
indent-width = 4
target-version = "py313"

# Excluir diretórios e arquivos específicos
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
]

[lint]
# Regras selecionadas para um projeto Flask
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
    "N",   # pep8-naming
    "C4",  # flake8-comprehensions
    "PIE", # flake8-pie
    "T20", # flake8-print
    "RET", # flake8-return
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PL",  # Pylint
    "TRY", # tryceratops
]

# Regras ignoradas (específicas para projetos Flask)
ignore = [
    "E402",   # Module level import not at top of file (comum em Flask)
    "F401",   # Imported but unused (comum em __init__.py)
    "B008",   # Do not perform function calls in argument defaults
    "N806",   # Variable in function should be lowercase (para compatibilidade com MongoDB)
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
    "TRY003",  # Avoid specifying long messages outside the exception class
    "T201",    # print found (permitir prints para debug)
    "ERA001",  # Found commented-out code
]

# Configurações específicas por regra
[lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]  # Permitir imports não utilizados em __init__.py
"src/main.py" = ["F401"]         # Permitir imports de módulos de rotas
"*/migrations/*" = ["ALL"]       # Ignorar todas as regras em migrações
"tests/*" = ["ARG", "PLR2004"]   # Relaxar regras em testes

# Configurações do isort
[lint.isort]
known-first-party = ["src", "db", "functions"]
known-third-party = ["flask", "pymongo", "pandas", "reportlab"]
split-on-trailing-comma = true

# Configurações do flake8-quotes
[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"

# Configurações de formatação
[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

# Configurações do docstring
[lint.pydocstyle]
convention = "google"
