services:
  app:
    build: .
    container_name: app-novela
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db-novela:27017/cpppac
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: db-novela
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge