version: '3'

services:
  app:
    image: fedora:latest
    container_name: app-novela
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db-novela:27017/cpppac
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: db-novela
    ports:
      - 27017:27017
    volumes:
      - /db:/db
    restart: always


volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge