name: Novela em CI/CD

on:
  push:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install flask flask-pymongo flask-wtf; fi
    
    - name: Lint files
      run: |
        ruff format src/rotas.py 
        ruff format src/rotas_saida.py
        ruff format src/main.py 
        flake8 rotas.py --count --select=E9,F63,F7 --show-source --statistics
        flake8 rotas_saida.py --count --select=E9,F63,F7--show-source --statistics
        flake8 main.py --count --select=E9,F63,F7--show-source --statistics

  Deploy_db:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: ./db/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/db_novela:v0.${{github.run_number}}


  Deploy_app:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/novela:v0.${{github.run_number}}

#PARA CONSERTAR O HUB DO DOCKER !
